services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/reservation-api-app:v1
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - .:/app
  
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/mysql/mysql-data:/var/lib/mysql