version: '3.8'

services:
  neo4j:
    image: neo4j:community  
    ports:
      - "7475:7474"
      - "7689:7687"
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins