services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - neo4j
      - mysql

  neo4j:
    image: neo4j:5.21.0-community 
    ports:
      - "7475:7474"
      - "7689:7687"
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./db/neo4j/data:/data
      - ./db/neo4j/conf:/conf
      - ./db/neo4j/logs:/logs
      - ./db/neo4j/plugins:/plugins
  
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fieldsapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/mysql:/var/lib/mysql