from .account_repository import AccountRepositoryInterface
from .login_repository import LoginRepositoryInterface
from .person_repository import PersonRepositoryInterface
from .rol_repository import RoleRepositoryInterface
