apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migration
spec:
  template:
    metadata:
      name: alembic-migration
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 $MYSQL_HOST $MYSQL_PORT; do echo waiting for mysql; sleep 2; done;']
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_PORT
          value: "3306"
      containers:
      - name: alembic-migration
        image: darlackinho/reservation-api-app:v1
        command: ["alembic", "upgrade", "head"]
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-database