apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: fastapi-app:latest
        ports:
        - containerPort: 8000
      env:
      - name: DATABASE_URL
        value: "mysql://${DB_USER}:${DB_PASSWORD}@mysql-service:3306/${DB_NAME}"
