from .account_mysql_repository import AccountMySQLRepository
from .login_mysql_repository import LoginMySQLRepository
from .person_mysql_repository import PersonMySQLRepository
from .rol_mysql_repository import RolMySQLRepository
