name: CI/CD

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          make test

      - name: Build Docker image
        run: |
          make build
      
      - name: Push Docker image
        run: |
          make docker-push VERSION=${{ github.sha }}
      
      - name: Deploy to Minikube
        run: |
          make local-deploy VERSION=${{ github.sha }}


      